name: Promote to UAT (RC)
on:
  push:
    tags:
      - 'RC*'

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: '905418330989'

jobs:
  promote-to-uat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Parse RC manifest
        id: parse_rc
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Load manifest
        id: get_QA_version
        run: |
          RC_MANIFEST="release-manifests/${{ steps.parse_rc.outputs.tag }}.yaml"
          echo "Using manifest file: $RC_MANIFEST"

          # Convert YAML to JSON
          SERVICES_JSON=$(yq -o=json .services "$RC_MANIFEST")

          FINAL_PAYLOAD=$(echo "$SERVICES_JSON" | jq --arg acc "${{ env.AWS_ACCOUNT_ID }}" --arg reg "${{ env.AWS_REGION }}" '
            with_entries(
              .value = "\($acc).dkr.ecr.\($reg).amazonaws.com/\(.key):\(.value)"
            )
          ')

          echo "services_json=${FINAL_PAYLOAD}" >> $GITHUB_OUTPUT

      - name: Debug JSON
        run: |
          echo "Debugging JSON"
          echo "${ steps.get_QA_version.outputs.services_json }"

      # - name: Notify Infra Repo (QA)
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token: ${{ secrets.INFRA_REPO_TOKEN }}
      #     repository: aawihardja-usfca/microservice2-infra
      #     event-type: deploy-UAT
      #     client-payload: |
      #       ${{  steps.get_QA_version.outputs.services_json }}