name: Promote to Production (GA)
on:
  push:
    tags:
      - 'GA-*'  # e.g. GA-1.0, GA-1.2

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: '905418330989'

jobs:
  promote-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract GA tag
        id: parse_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Read GA manifest to get base RC
        id: read_ga_manifest
        run: |
          MANIFEST="release-manifests/${{ steps.parse_tag.outputs.tag }}.yaml"
          echo "Reading GA manifest: $MANIFEST"
          
          BASE_RC=$(yq .base "$MANIFEST")
          echo "base=$BASE_RC" >> $GITHUB_OUTPUT

      - name: Read RC manifest to get QA image tags
        id: parse_rc_manifest
        run: |
          RC_MANIFEST="release-manifests/${{ steps.read_ga_manifest.outputs.base }}.yaml"
          echo "Reading RC manifest: $RC_MANIFEST"

          # Convert services YAML to JSON and construct full image URIs
          SERVICES_JSON=$(yq -o=json .services "$RC_MANIFEST")

          for SERVICE in $(echo "$SERVICES_JSON" | jq -r 'keys[]'); do
            TAG=$(echo "$SERVICES" | jq -r --arg s "$SERVICE" '.[$s]')
            IMAGE_URI="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$SERVICE:$TAG"
            echo "$SERVICE=$IMAGE_URI" >> $GITHUB_OUTPUT
          done

      - name: Notify Infra Repo (GA deploy)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          repository: aawihardja-usfca/microservice2-infra
          event-type: deploy-Production
          client-payload: |
            {
              "frontend": "${{ steps.parse_rc_manifest.outputs.frontend }}",
              "auth-api": "${{ steps.parse_rc_manifest.outputs.auth-api }}",
              "users-api": "${{ steps.parse_rc_manifest.outputs.users-api }}",
              "todos-api": "${{ steps.parse_rc_manifest.outputs.todos-api }}",
              "log-message-processor": "${{ steps.parse_rc_manifest.outputs.log-message-processor }}"
            }
