name: Promote to UAT (RC)
on:
  push:
    tags:
      - 'RC*'

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: '905418330989'

jobs:
  promote-to-uat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Parse RC manifest
        id: parse_rc
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Load manifest
        id: get_QA_version
        run: |
          MANIFEST="release-manifests/${{ steps.parse_rc.outputs.tag }}.yaml"
          echo "Using manifest file: $MANIFEST"

          # Convert YAML to JSON
          SERVICES=$(yq -o=json .services "$MANIFEST")

          echo "services_json=${SERVICES_JSON}" >> $GITHUB_OUTPUT

      - name: Notify Infra Repo (QA)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          repository: aawihardja-usfca/microservice2-infra
          event-type: deploy-UAT
          client-payload: |
            ${{  steps.get_QA_version.outputs.services_json }}