name: Promote to Production (GA)
on:
  push:
    tags:
      - 'GA-*'

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: '905418330989'

jobs:
  promote-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract GA tag
        id: parse_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Read GA manifest to get base RC
        id: read_ga_manifest
        run: |
          MANIFEST="release-manifests/${{ steps.parse_tag.outputs.tag }}.yaml"
          echo "Reading GA manifest: $MANIFEST"
          
          BASE_RC=$(yq .base "$MANIFEST")
          echo "base=$BASE_RC" >> $GITHUB_OUTPUT

      - name: Read RC manifest to get QA image tags
        id: build_payload
        run: |
          RC_MANIFEST="release-manifests/${{ steps.read_ga_manifest.outputs.base }}.yaml"
          echo "Reading RC manifest: $RC_MANIFEST"

          # Convert services YAML to JSON and construct full image URIs
          SERVICES_JSON=$(yq -o=json .services "$RC_MANIFEST")
          FINAL_PAYLOAD=$(echo "$SERVICES_JSON" | jq --arg acc "${{ env.AWS_ACCOUNT_ID }}" --arg reg "${{ env.AWS_REGION }}" '
            with_entries(
              .value = "\($acc).dkr.ecr.\($reg).amazonaws.com/\(.key):\(.value)"
            )
          ')

          echo "services_json=$FINAL_PAYLOAD" >> $GITHUB_OUTPUT
          echo "$FINAL_PAYLOAD" > payload.json

      - name: Notify Infra Repo (GA deploy)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          repository: aawihardja-usfca/microservice2-infra
          event-type: deploy-Production
          client-payload: ${{ steps.build_payload.outputs.services_json }}
